services:
  gotravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tours_gotravel
    restart: always
    ports:
      - "3005:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MYSQL_HOST=gotravel_db
      - MYSQL_PORT=3306
      - MYSQL_USER=gotravel_user
      - MYSQL_PASSWORD=GoTravelSecretPass2026!
      - MYSQL_DATABASE=gotravel_db
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: gotravel_db
    restart: always
    command: --default-authentication-plugin=mysql_native_password --sort_buffer_size=4M --max_allowed_packet=64M
    environment:
      MYSQL_ROOT_PASSWORD: GoTravelRootPass2026!
      MYSQL_DATABASE: gotravel_db
      MYSQL_USER: gotravel_user
      MYSQL_PASSWORD: GoTravelSecretPass2026!
    ports:
      - "3307:3306"
    volumes:
      - mysql_gotravel_data:/var/lib/mysql

volumes:
  mysql_gotravel_data:
